#!/bin/sh
### BEGIN INIT INFO
# Provides:          mercury
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     3 4 5
# Default-Stop:
# Short-Description: Starts processes to run the mercury instrument panel
# Description:       Starts processes to run the mercury instrument panel.
#                    These processes communicate with each other via FIFIs.
### END INIT INFO

##########################################################
# Install this script as follows:
#   sudo cp mercury /etc/init.d
#   sudo update-rc.d mercury defaults
#
# Stop is not implemented and 
# there is no checking to make sure not already started
##########################################################

do_start () {
        /home/pi/mercury/src/mercury_run.sh
}


case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  status)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  *)
	echo "Usage: mercury [start|stop|status]" >&2
	exit 3
	;;
esac

:
